version: "3.8"

services:

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - adminer
      - basicphp
#      - hypixelzcomparator
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "443:443"
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - "./portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:9000"

  db:
    image: postgres:9.6-stretch
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - "./postgres/data:/var/lib/postgresql/data"
      - "/usr/local/etc/php/:/"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "5000:5000"

#  Only uncomment this block if you have access to project
  discordbot:
    build:
      context: ./discordBot
    container_name: discordbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - "./discordBot/:/home/app/"
    restart: always

# Should only be used on local as it show phpinfo()
  basicphp:  
    build:
      context: ./website
    container_name: basic-php
    volumes:
      - "./website/basicphp:/var/www/html"

#  Only uncomment this block if you have access to project
  hypixelzcomparator:  
    build:
      context: ./website
    container_name: hypixelzcomparator
    environment:
      - DB_URL=db
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "./website/HypixelzComparator:/var/www/html"